### ISSUE TITLE
How to - other examples

### ISSUE THREAD

**Issue by lijecaru** [mellocolate/carla-display-backend#29]
You show one example from another person on the usage of the tool. How can one display the camera image and the pose/trajectoy information of the vehicle on the visualization? Do I have to use rosbridge to get this information as topics?

**Comment by wx9698** [comment]
1. To display the image, just spawn a camera in your client python script. Currently this backend only supports one RGB camera (sensor.camera.rgb). If you have multiple cameras in your script, it will display one randomly. I will add multiple camera support in the near future.
2. To display the trajectory, I have created a python api that can connect to this backend and transmit the trajectory data for visualization. I will add this api package to this repo later.
3. I don't understand what do you mean by the pose information. Do you mean that how to display the vehicle in the center of the screen?

**Comment by wx9698** [comment]
Hi, I have moved all contents to another repo - [carlaviz](https://github.com/wx9698/carlaviz). You can follow the examples there to draw your trajectories, display the pose information, etc.. 

And you don't need to use rosbridge at all.
